### ISSUE TITLE
请问构建npm完了之后报Uncaught Error: module "miniprogram_npm/xmlhttprequest-ssl/fs" is not defined如何解决？

### ISSUE THREAD

**Issue by hnxzc** [holytiny/feathersjs-wxmp-socket.io-client#3]
感谢作者！

**Comment by enderson-pan** [comment]
const socketioInit = io('http://localhost', {
    transports: ['websocket']
  });

只支持websocket传输层，需要在初始化的时候显示指定。微信小程序环境下，如果不显示指定，socket.io-client会优先使用http连接。

**Comment by hnxzc** [comment]
> const socketioInit = io('http://localhost', {
> transports: ['websocket']
> });
> 
> 只支持websocket传输层，需要在初始化的时候显式指定。微信小程序环境下，如果不显示指定，socket.io-client会优先使用http连接。
> 可以看一下代码示例。https://github.com/holytiny/feathersjs-wxmp-socket.io-client

在微信小程序环境下，我用的是wss://的url，服务器端nginx转发到http的3000端口上面，服务端监听3000端口。
现在是在小程序开发工具编译时就报错Uncaught Error: module "miniprogram_npm/xmlhttprequest-ssl/fs" is not defined，显式指定websocket也报错。

**Comment by hnxzc** [comment]
对了，我是单独使用的wxmp-socket.io-client。

**Comment by enderson-pan** [comment]
明白了。现在的测试用例里面没有测试ssl，我测试一下。如果有问题马上会修复。

**Comment by enderson-pan** [comment]
问题找到了，因为微信小程序的npm打包工具不支持nodejs库。需要用webpack打包后再加入工程。正在解决中。
